name: vagrant-up

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  vagrant-up:
    runs-on: macos-12
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
